name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }} #https://stackoverflow.com/questions/62334460/git-history-in-a-github-action
        fetch-depth: 0
    - name: Check whether merge request has been performed
      id: check-merge
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check whether merge request has been performed
        setup-command:
        command: if git log --oneline --all | grep Merge; then echo "merge found"; else echo "No merge found"; exit 1; fi
        timeout: 10
        max-score: 10
    - name: Check notebook
      id: check-notebook
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check notebook
        setup-command: pip install numpy scipy pandas matplotlib jupyter ipykernel pip
        command: jupyter nbconvert --execute PA_1_5_useful_tricks.ipynb --to html
        timeout: 10
        max-score: 10
    - name: Check for figure in myfigure.md
      id: check-figure
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check for figure in myfigure.md
        setup-command: 
        command: if grep -q '!\[' myfigure.md; then echo "Figure found in myfigure.md"; else echo "No figure found in myfigure.md"; exit 1; fi
        timeout: 10
        max-score: 10
    - name: Check for 'my_figure.svg' in \figures\
      id: check-figure-sub
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check for 'my_figure.svg' in \figures\
        setup-command: 
        command: if test -f figures/my_figure.svg; then echo "File figures/my_figure.svg found"; else echo "file figures/my_figure.svg not found"; exit 1; fi 
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-MERGE_RESULTS: "${{steps.check-merge.outputs.result}}"
        CHECK-NOTEBOOK_RESULTS: "${{steps.check-notebook.outputs.result}}"
        CHECK-FIGURE_RESULTS: "${{steps.check-figure.outputs.result}}"
        CHECK-FIGURE-SUB_RESULTS: "${{steps.check-figure-sub.outputs.result}}"
      with:
        runners: check-merge,check-notebook,check-figure,check-figure-sub